### ISSUE TITLE
uniform_int_distribution is not guaranteed to produce consistent results across platforms

### ISSUE THREAD

**Issue by bluebear94** [WishMakers0/Danmakufu-Woo-Edition#4]
From [rand.dist.general] in [C++17 standard draft](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4659.pdf):

> The algorithms for producing each of the specified distributions are implementation-defined.

I don't know whether this is a problem for this project since it's not very likely to be built by anything but MSVC, but still something to keep in mind.

**Comment by WishMakers0** [comment]
Thank you for letting me know - I'll keep that in mind for RNG implementation in DNH:R, since MSVC should be the only way this is compiled.  (It's not like mkm's code is portable enough for other compilers and architectures anyway)
